site_name: Sistema de Guardias y Presencia
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate

nav:
  - Inicio: index.md
  - Arquitectura del sistema: arquitectura.md
  - Base de Datos (SQLite): base_datos.md
  - Módulo Flask: flask.md
  - Módulo de Guardias:
      - Motor de cálculo: guardias.md
  - Módulo de Presencia: presencia.md
  - Pruebas unitarias con pytest: pruebas.md
  - Despliegue en Raspberry Pi: despliegue.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
